import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const googleTagId = process.env.NEXT_PUBLIC_GOOGLE_TAG_ID;
  const metaPixelId = process.env.NEXT_PUBLIC_META_PIXEL_ID;

  return (
    <html lang="es">
      <head>

        {/* Meta Pixel Base Code */}
            <Script id="fb-pixel" strategy="afterInteractive"> {/**strategy="afterInteractive":hace que el Píxel cargue justo después de que la página sea interactiva, para no ralentizar la velocidad de carga */}
              {`
                !function(f,b,e,v,n,t,s) 
                {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                n.queue=[];t=b.createElement(e);t.async=!0;
                t.src=v;s=b.getElementsByTagName(e)[0];
                s.parentNode.insertBefore(t,s)}(window, document,'script',
                'https://connect.facebook.net/en_US/fbevents.js');
                fbq('init', '${metaPixelId}'); 
                fbq('track', 'PageView');
              `}
              {/*
              *Notas:
              *!function(f,b,e,v,n,t,s)...: Es un código "minificado" que instala la función fbq en el navegador. Prepara el terreno para que Facebook pueda escuchar.
              *t.async=!0; t.src=v;: Carga el archivo de Meta de forma asíncrona para no bloquear el diseño de la página.
              *fbq('init', '${metaPixelId}'): pegar el ID numérico del cliente (de su cuenta de Meta Business Suite) 
              *fbq('track', 'PageView'): Registra que alguien entró a la web, independientemente de si compró o no 
              */}
            </Script>
        {/* Google Tag (gtag.js) */}
            {googleTagId && (
              <>
                <Script
                  src={`https://www.googletagmanager.com/gtag/js?id=${googleTagId}`} //Descarga la librería principal de Google desde sus servidores usando el ID del cliente.
                  strategy="afterInteractive"
                />
                <Script id="google-analytics" strategy="afterInteractive"> {/**strategy="afterInteractive: El script sólo se carga después que el usuario pueda hacer clic en botones*/}
                  {`
                    window.dataLayer = window.dataLayer || []; 
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());
                    gtag('config', '${googleTagId}');
                  `}
                  {/*
                   * window.dataLayer: Crea un "almacén" de datos en el navegador donde se guardarán todas las acciones del usuario (clics, compras, etc.).
                   * gtag('js', new Date());: Registra la hora exacta en la que se activó el rastreo.
                   * gtag('config', '${googleTagId}');: Vincula oficialmente la web con la cuenta de Google Analytics del cliente.
                  */}
                </Script>
              </>
            )}    
       
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
